export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR";
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const ADMIN_DATA_LOAD = "ADMIN_DATA_LOAD";

//PROFILE REDUCER
export const AUTH_USER_LOAD = "AUTH_USER_LOAD";
export const AUTH_USER_LOAD_ERROR = "AUTH_USER_LOAD_ERROR";
export const PROFILE_UPDATE = "PROFILE_UPDATE";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const PASSWORD_CHANGED_ERROR = "PASSWORD_CHANGED_ERROR";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

//GROUP REDUCER
export const GET_GROUPS_OF_AUTH_USER_SUCCESS =
  "GET_GROUPS_OF_AUTH_USER_SUCCESS";
export const GET_GROUPS_OF_AUTH_USER_FAIL = "GET_GROUPS_OF_AUTH_USER_FAIL";
export const CREATE_GROUP = "CREATE_GROUP";

//PROBLEMS
export const CREATE_PROBLEM = "CREATE_PROBLEM";
export const GET_PROBLEM_ALL = "GET_PROBLEM_ALL";
export const DELETE_PROBLEM = "DELETE_PROBLEM";
export const EDIT_PROBLEM = "EDIT_PROBLEM";
